CREATE DATABASE SCOPED CREDENTIAL CredencialBBDD WITH IDENTITY = 'SHARED ACCESS SIGNATURE',SECRET = '#DATALAKESTORAGEKEY#'
CREATE EXTERNAL DATA SOURCE DataLakeExterno WITH (LOCATION = 'wasbs://wwi-02@#DATALAKESTORAGEACCOUNTNAME#.blob.core.windows.net',CREDENTIAL = CredencialBBDD,TYPE = HADOOP)
CREATE EXTERNAL FILE FORMAT csv WITH (FORMAT_TYPE = DELIMITEDTEXT,FORMAT_OPTIONS (FIELD_TERMINATOR = ',',STRING_DELIMITER = '',DATE_FORMAT = '',USE_TYPE_DEFAULT = False))
